# Generated by Django 2.2.4 on 2019-09-01 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='comapny_email',
        ),
        migrations.RemoveField(
            model_name='company',
            name='comapny_telephone',
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(default=None, upload_to='company_images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='avtar',
            field=models.ImageField(default=None, upload_to='user_images'),
            preserve_default=False,
        ),
    ]
