# Generated by Django 2.2.4 on 2019-09-06 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20190901_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='comapny_address',
            field=froala_editor.fields.FroalaField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_company', to=settings.AUTH_USER_MODEL),
        ),
    ]
