# Generated by Django 2.2.4 on 2019-09-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20190906_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='comapny_address',
            field=models.TextField(max_length=200),
        ),
    ]
