# Generated by Django 2.2.4 on 2019-09-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_auto_20190918_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_website',
            field=models.TextField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
