# Generated by Django 2.2.4 on 2019-08-30 03:19

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='invoive_no')),
                ('invoive_no', models.CharField(max_length=50)),
                ('invoice_date', models.DateTimeField()),
                ('due_date', models.DateTimeField()),
                ('tax', models.FloatField()),
                ('discount', models.FloatField()),
                ('notes', models.TextField(max_length=500)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='customer.Customer')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='service')),
                ('service', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('quantity', models.FloatField()),
                ('unit_price', models.FloatField()),
                ('price', models.FloatField()),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_items', to='invoice.Invoice')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
    ]
