# Generated by Django 2.2.4 on 2019-09-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
