# Generated by Django 2.2.4 on 2019-09-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20190918_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='webiste',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
